#205: feat: Possibilité d'utiliser des composants basiques dans les cellule…
dnum-mi/vue-dsfr pull request #206
Opened 2022-01-06 17:32 UTC by gideruette

Possibilité d'utiliser des balises standards dans les cellules des tableaux

2022-01-10 15:57 UTC, laruiss requested changes

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.spec.js
> +      href: `/`,
eslint : single quote

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.spec.js
> +      "aria-label": "Vers la page d'accueil",
eslint: single-quote

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.spec.js
> +    const label = 'Label de l’étiquette'
`label` n’est utilisée nulle part

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.stories.js
> +  "aria-label": "Vers la page d'accueil",
eslint: single-quote

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.stories.js
> +export const CelluleDeTableauAvecComposantSimple = (args) => ({
`CelluleDeTableauAvecElementHtml`

2022-01-10 15:57 UTC, laruiss commented on src/components/DsfrTable/DsfrTableCell.vue
> +    {{ field.text }}
eslint : indentation

2022-01-12 10:24 UTC, plegaud approved these changes

2022-01-12 10:26 UTC, laruiss approved these changes

2022-01-12 10:27 UTC, merged