feat([DsfrAccordion]): :sparkles: Customisation du titre
dnum-mi/vue-dsfr pull request #299
Opened 2022-03-28 09:07 UTC by sophieaitis

Donner la possibilité de customiser le titre de l'accordéon

Fix: #298

2022-03-29 14:24 UTC, laruiss requested changes

2022-03-30 14:57 UTC, sophieaitis commented on src/components/DsfrAccordion/DsfrAccordion.vue
> +        </slot>
@laruiss C'est bon, c'est ajouté !

2022-03-31 08:27 UTC, laruiss approved these changes

2022-03-31 08:27 UTC, laruiss commented on src/components/DsfrAccordion/DsfrAccordion.vue
> +        </slot>
Super, merci !

2022-03-31 09:02 UTC, merged