feat(DsfrFooter): ✨ Ajout de props pour le logo opérateur
dnum-mi/vue-dsfr pull request #362
Opened 2022-05-02 12:30 UTC by Nanaki

2022-05-02 17:06 UTC, laruiss requested changes

2022-05-02 17:06 UTC, laruiss commented on src/components/DsfrFooter/DsfrFooter.stories.js
> +    :operatorImgAlt="operatorImgAlt"
Utiliser du kebab-case pour les noms des props

2022-05-02 17:06 UTC, laruiss commented on src/components/DsfrFooter/DsfrFooter.stories.js
> +    operatorTo: {
Il manque la documentation de `operatorLinkText` ici

2022-05-03 13:22 UTC, Nanaki commented on src/components/DsfrFooter/DsfrFooter.stories.js
> +    operatorTo: {
Description ajoutée :+1:

2022-05-03 13:22 UTC, Nanaki commented on src/components/DsfrFooter/DsfrFooter.stories.js
> +    :operatorImgAlt="operatorImgAlt"
Résolu via un git push -f pour garder un joli commit dans l'historique git.
Je résolve à la main.

2022-05-04 08:57 UTC, laruiss approved these changes

2022-05-04 09:01 UTC, merged