feat(DsfrHeader): ✨ Remplace le slot operator par des props pour le l…
dnum-mi/vue-dsfr pull request #364
Opened 2022-05-02 12:34 UTC by Nanaki

…ogo opérateur

2022-05-02 17:04 UTC, laruiss requested changes

2022-05-02 17:04 UTC, laruiss commented on src/components/DsfrHeader/DsfrHeader.vue
> +                >
Il faudrait laisser le slot operator, le laisser et mettre le contenu par défaut (l. `115` à `120`) à l’intérieur

2022-05-03 12:57 UTC, Nanaki commented on src/components/DsfrHeader/DsfrHeader.vue
> +                >
C'est fait (via un push -f pour garder un seul beau commit, donc je resolve à la main)

2022-05-04 08:56 UTC, laruiss requested changes

2022-05-04 08:56 UTC, laruiss commented on src/components/DsfrHeader/DsfrHeader.stories.js
> +      :operatorImgStyle="operatorImgStyle"
Il faudrait du kebab-case.
`operatorImgStyle` n’est pas documenté et ne semble pas être présent partout...

2022-05-04 08:56 UTC, laruiss commented on src/components/DsfrHeader/DsfrHeader.stories.js
> +    operatorImgSrc: {
et `operatorImgStyle` ?

2022-05-04 09:05 UTC, laruiss requested changes

2022-05-04 10:51 UTC, laruiss approved these changes

2022-05-04 10:53 UTC, merged