Dsfr tabs choix tab initial
dnum-mi/vue-dsfr pull request #382
Opened 2022-05-23 10:19 UTC by sophieaitis

2022-05-23 16:27 UTC, laruiss requested changes
Il faut rebaser sur `develop` et demander la fusion dans `develop`

2022-05-25 15:43 UTC, laruiss requested changes

2022-05-25 15:43 UTC, laruiss commented on src/components/DsfrTabs/DsfrTabs.stories.js
> +    initiallySelectedIndex: {
- Je veux bien simplifier en `initialSelectedIndex`
- Il faudrait rajouter cette props dans la définition du type correspondant : après la ligne 13 et la ligne 28 de `/types/components/DsfrTabs.vue.d.ts`

2022-05-30 13:59 UTC, sophieaitis commented on src/components/DsfrTabs/DsfrTabs.stories.js
> +    initiallySelectedIndex: {
C'est modifié !

2022-06-22 13:46 UTC, merged