fix(DsfrFieldset): Missing `fr-fieldset__element` elements to wrap Fieldset legend, hint and content
dnum-mi/vue-dsfr pull request #455
Opened 2023-01-18 14:37 UTC by ambroisemaupate

- Actuellement
![image](https://user-images.githubusercontent.com/380026/213199548-77c34cbf-801e-4a15-bbea-a6a58ac0f637.png)

- Devrait ressembler à 
![image](https://user-images.githubusercontent.com/380026/213199434-1459ea44-b085-40e5-a0c8-cd6cc770754e.png)

Exemple d'intégration: https://www.systeme-de-design.gouv.fr/elements-d-interface/modeles-et-blocs-fonctionnels/modele-de-page-de-creation-de-compte

2023-01-19 11:30 UTC, laruiss requested changes

2023-01-19 11:30 UTC, laruiss commented on src/components/DsfrFieldset/DsfrFieldset.stories.js
> +        <h6>{{ legend }} avec <em>de l’italique</em> dans un titre</h6>
On devrait pouvoir changer le niveau de cette balise `h*`, car pour la validation RGAA on ne doit pas passer de h3 à h6...
Regarde ce qu’on a fait pour DsfrAlert et la props `titleTag`.

2023-01-19 11:30 UTC, laruiss commented on src/components/DsfrFieldset/DsfrFieldset.stories.js
> +        <h6>{{ legend }} avec <em>de l’italique</em> dans un titre</h6>
J’ai oublié : merci pour cette PR !

2023-01-19 11:33 UTC, ambroisemaupate commented on src/components/DsfrFieldset/DsfrFieldset.stories.js
> +        <h6>{{ legend }} avec <em>de l’italique</em> dans un titre</h6>
C'etait juste un exemple dans la story, je pense que les `h*` dans la legend doivent rester facultatifs.

2023-01-20 14:20 UTC, laruiss commented on src/components/DsfrFieldset/DsfrFieldset.stories.js
> +        <h6>{{ legend }} avec <em>de l’italique</em> dans un titre</h6>
Ah oui, très bien, mes excuses !

2023-01-20 14:22 UTC, laruiss approved these changes

2023-01-20 14:22 UTC, merged

2023-01-20 14:23 UTC, ambroisemaupate commented on src/components/DsfrFieldset/DsfrFieldset.stories.js
> +        <h6>{{ legend }} avec <em>de l’italique</em> dans un titre</h6>
Super, merci pour tes reviews