feat: :sparkles: Ajout d'un slot dans le composant header + fix icons…
dnum-mi/vue-dsfr pull request #509
Opened 2023-03-13 14:02 UTC by DaBadBunny

… storybook

Ajout d'un slot dans le composant header pour y intégrer le composant navigation et ajout du css manquant pour visualiser les icones officielles dans le storybook

2023-03-13 15:36 UTC, laruiss requested changes

2023-03-13 15:36 UTC, laruiss commented on .storybook/preview.js
> +import '../src/main.css'
Ce serait mieux de rajouter :

```javascript
import '@gouvfr/dsfr/dist/utility/utility.main.min.css'
import '@gouvfr/dsfr/dist/utility/icons/icons.main.min.css'
```

Et de totalement supprimer `src/main.css`

2023-03-13 15:54 UTC, laruiss commented on .storybook/preview.js
> +import '../src/main.css'
Ah, il n’est plus utilisé, ce `build-css.mjs`... Tu peux l’effacer aussi !

2023-03-13 15:55 UTC, DaBadBunny commented on .storybook/preview.js
> +import '../src/main.css'
Niquel :D

2023-03-13 16:29 UTC, laruiss approved these changes

2023-03-13 16:29 UTC, merged

2023-03-14 10:03 UTC, cailliaud commented
Merci @DaBadBunny pour cette PR 👍