=feat: added the ability to set the row key
dnum-mi/vue-dsfr pull request #712
Opened 2023-12-28 06:25 UTC by AbanoubNassem

[feat]: added the ability to set the row key , so when new data fetched the table updates correctly , becuase currently `table-row` relies on the index of the loop which is not correct

2023-12-28 09:54 UTC, laruiss commented
Merci beaucoup pour votre contribution !
Cette bibliothèque étant strictement franco-française, nous avons décidé dès le départ que toute la documentation soit en français (obligation légale, d’ailleurs), ainsi que tous les messages de commit, les tickets, les discussions, et le commentaires de PR.
D’autre part, les messages de commit ne respectent pas les conventions [conventional commits](https://www.conventionalcommits.org/fr/v1.0.0/). Dès que vous aurez modifié cela, nous pourrons fusionner votre PR et publier ensuite une nouvelle version de la bibliothèque !

2023-12-28 10:18 UTC, AbanoubNassem commented
@laruiss 

Merci pour vos commentaires. J'ai fait de mon mieux pour traduire la demande d'extraction en français. N'hésitez pas à apporter des modifications à la demande d'extraction afin qu'elle soit conforme à l'intention initiale, car mes connaissances en français sont limitées

2024-01-04 11:00 UTC, laruiss requested changes
Il faudrait :
- enlever les `=` devant les messages de commit (très important)
- mettre les messages de commit en français (important)
- respecter conventional commit pour tous les commits (très important pour le dernier `feat:...`)

Et ensuite on fusionne ça

Please do this :
- remove the `=` at the start of your commit messages (very important)
- put the commit messages in french (important)
- respect the conventions of conventional commit for all commits (very important for the last one `feat:...`)

And then we can merge

2024-01-04 11:15 UTC, AbanoubNassem reviewed
👍

2024-01-05 09:19 UTC, laruiss commented
> @laruiss
> 
> > Please do this :
> 
> > remove the = at the start of your commit messages (very important)
> > put the commit messages in french (important)
> > respect the conventions of conventional commit for all commits (very important for the last one feat:...)
> 
> I think I have done that , did I miss something ?

Unfortunately, the commit messages are still beginning with `=` while they should be of the following form:
`<type>[optional scope]: <description>`

with `type` being one of `fix`, `feat` `build`, `chore`, `ci`, `docs`, `style`, `refactor`, `perf`, `test`.

So this: 
` =feat: added the ability to set the row key , so when new data fetched the table updates correctly`

Should be:
 `feat: ajoute la possibilité d’indiquer la clé de ligne dans le tableau de données
 
 - permet que le tableau soit bien mis à jour à chaque changement de données`
 
![image](https://github.com/dnum-mi/vue-dsfr/assets/2486424/f08e822f-37e6-4f92-8ba9-e1f2164172ce)

2024-01-05 10:55 UTC, AbanoubNassem commented
@laruiss 

ah the commit message , sorry I thought , you meant the Pull-Request  title, please check now .

2024-01-05 11:54 UTC, merged