Fix: 🐛 Amélioration de quelques composants suite audit RGAA
dnum-mi/vue-dsfr pull request #982
Opened 2024-11-26 09:37 UTC by vincentlaine

2024-11-26 14:32 UTC, laruiss requested changes

2024-11-26 14:32 UTC, laruiss commented on src/composables/useCollapsable.ts
>      }
Je préférerais

```ts
  if (!collapse.value) {
    return
  }
  collapse.value.querySelector('a')?.focus()
  if (expanded === false) {
    collapse.value.style.removeProperty('--collapse-max-height')
  }
```

2024-11-26 14:32 UTC, laruiss commented on src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
> -      :aria-controls="breadcrumbId"
Pourquoi supprimer ces attributs ?

2024-11-26 15:08 UTC, vincentlaine commented on src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
> -      :aria-controls="breadcrumbId"
Je suis pas expert en accessibilité mais c'était dans les recommandations du rapport : 

Problème
● 7.1 - majeur : présence d’un état plié (aria-expanded=”false”) non pertinent
Solution
● Supprimer l’attribut aria-expanded
● Supprimer l’attribut aria-controls

2024-12-05 13:48 UTC, laruiss requested changes

2024-12-05 13:48 UTC, laruiss commented on src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
> -      :aria-controls="breadcrumbId"
Il faut remplacer le `v-show` par `v-if`, ce sera plus propre et ça respectera les recommandations (le bouton ne sera pas rendu)

2024-12-12 13:59 UTC, vincentlaine commented on src/components/DsfrBreadcrumb/DsfrBreadcrumb.vue
> -      :aria-controls="breadcrumbId"
J'ai pas vu le mail de github passé, c'est bon je viens de le faire !

2024-12-18 20:15 UTC, laruiss approved these changes

2024-12-18 20:16 UTC, merged